# This is a basic workflow to help you get started with Actions
name: CI-build-and-push-image-for-dotnetapp

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      -
      version: '3.9'
services:
  ModusGoAPI:
    image: modustech/modusgo:apilatest
    ports:
      - 2181:80
    environment:
      - TZ=America/New_York
    volumes:
      - Modus-api:/app
    restart: always
    networks:
      - Modusgo
  ModusGoWeb:
    image: modustech/modusgo:weblatest
    ports:
      - 2180:80
    environment:
      - TZ=America/New_York
    volumes:
      - Modus-web:/usr/share/nginx/html
    restart: always
    networks:
      - Modusgo
volumes:
  Modus-api:
  Modus-web:
networks:
  Modusgo:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./modusgo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/modusgotestappweb:latest, ${{ secrets.DOCKERHUB_USERNAME }}/dockerfordotnetapi:${{ github.run_number }}
